name: Publish API Docs

on:
  # Manally run
  workflow_dispatch:
  # Pull request events for checking API docs
  pull_request:
  # Scheduled events for nightly API docs
  schedule:
    # UTC 00:00 everyday
    - cron: "0 0 * * *"
  # Events for API docs of new release
  push:
    branches:
      - main
    paths:
      - VERSION
  
jobs: 
  check_api_docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps: 
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix

      - name: Check API docs of crates to publish
        if: github.event_name == 'pull_request'
        run: nix run .#publish-api-docs --no-write-lock-file -- --dry-run

      - name: Check API docs of all crates
        run: nix run .#docs --no-write-lock-file

      - name: Build & Upload Nightly API Docs
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        env:
          API_DOCS_NIGHTLY_PUBLISH_KEY: ${{ secrets.API_DOCS_NIGHTLY_PUBLISH_KEY }}
        run: |
          KEY_FILE=./api_docs_nightly_publish_key
          echo "$API_DOCS_NIGHTLY_PUBLISH_KEY\n" > ${KEY_FILE}
          nix run .#publish-api-docs --no-write-lock-file -- nightly ${KEY_FILE}

      - name: Build & Upload Release API Docs
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          API_DOCS_PUBLISH_KEY: ${{ secrets.API_DOCS_PUBLISH_KEY }}
        run: |
          KEY_FILE=./api_docs_publish_key
          echo "$API_DOCS_PUBLISH_KEY\n" > ${KEY_FILE}
          nix run .#publish-api-docs --no-write-lock-file -- release ${KEY_FILE}
