name: Test Nix development environment

on:
  pull_request:
    paths:
      - ".github/workflows/test_devcontainer.yml"
      - ".github/actions/setup-nix/**"
      - "flake.lock"
      - "flake.nix"
      - "nix/**"
      - "rust-toolchain.toml"
  push:
    branches: [main]
    paths:
      - ".github/workflows/test_devcontainer.yml"
      - ".github/actions/setup-nix/**"
      - "flake.lock"
      - "flake.nix"
      - "nix/**"
      - "rust-toolchain.toml"

jobs:
  test-nix-dev-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
      - name: Verify Nix development shell
        run: |
          nix develop --no-write-lock-file -c bash -c '
            rustc --version
            cargo --version
            cargo osdk --version
            qemu-system-x86_64 --version
          '
