name: Test Asterinas Vsock

on:
  workflow_dispatch:

jobs:
  vsock-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix

      - name: Run Vsock Server on Host
        id: host_vsock_server
        run: |
          nix develop --no-write-lock-file -c bash -s <<'EOF'
            sudo modprobe vhost_vsock
            echo "Run vsock server on host...."
            server_cmd="while read cmd; do result=\$(eval \"\$cmd\" 2>&1); echo \"\$result\"; done"
            socat -ddd VSOCK-LISTEN:1234,fork \
              SYSTEM:"$server_cmd" &
          EOF
      - name: Run Vsock Client and Server on Guest
        id: guest_vsock_client_server
        run: |
            AUTO_TEST=vsock ENABLE_KVM=0 SCHEME=microvm RELEASE=1 \
              nix run .#run-kernel --no-write-lock-file &
      - name: Run Vsock Client on Host
        id: host_vsock_client
        run: |
          nix develop --no-write-lock-file -c bash -s <<'EOF'
          sleep 6m
          echo "Run vsock client on host...."
          echo "Hello from host" | socat -dd - vsock-connect:3:4321
          EOF
